// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: whiteboardmsg.proto

package com.hengqian.whiteboard.msg;

public final class Whiteboardmsg {
  private Whiteboardmsg() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  /**
   * Protobuf enum {@code com.hengqian.whiteboard.msg.TypeCommand}
   */
  public enum TypeCommand
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>DrawPoint = 10001;</code>
     *
     * <pre>
     * 画点
     * </pre>
     */
    DrawPoint(0, 10001),
    /**
     * <code>DrawUndo = 10002;</code>
     *
     * <pre>
     * 撤销一步
     * </pre>
     */
    DrawUndo(1, 10002),
    /**
     * <code>DrawClearAll = 10003;</code>
     *
     * <pre>
     * 清屏
     * </pre>
     */
    DrawClearAll(2, 10003),
    /**
     * <code>DrawQuit = 10004;</code>
     *
     * <pre>
     * 退出
     * </pre>
     */
    DrawQuit(3, 10004),
    ;

    /**
     * <code>DrawPoint = 10001;</code>
     *
     * <pre>
     * 画点
     * </pre>
     */
    public static final int DrawPoint_VALUE = 10001;
    /**
     * <code>DrawUndo = 10002;</code>
     *
     * <pre>
     * 撤销一步
     * </pre>
     */
    public static final int DrawUndo_VALUE = 10002;
    /**
     * <code>DrawClearAll = 10003;</code>
     *
     * <pre>
     * 清屏
     * </pre>
     */
    public static final int DrawClearAll_VALUE = 10003;
    /**
     * <code>DrawQuit = 10004;</code>
     *
     * <pre>
     * 退出
     * </pre>
     */
    public static final int DrawQuit_VALUE = 10004;


    public final int getNumber() { return value; }

    public static TypeCommand valueOf(int value) {
      switch (value) {
        case 10001: return DrawPoint;
        case 10002: return DrawUndo;
        case 10003: return DrawClearAll;
        case 10004: return DrawQuit;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<TypeCommand>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<TypeCommand>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<TypeCommand>() {
            public TypeCommand findValueByNumber(int number) {
              return TypeCommand.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.hengqian.whiteboard.msg.Whiteboardmsg.getDescriptor().getEnumTypes().get(0);
    }

    private static final TypeCommand[] VALUES = values();

    public static TypeCommand valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private TypeCommand(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:com.hengqian.whiteboard.msg.TypeCommand)
  }

  /**
   * Protobuf enum {@code com.hengqian.whiteboard.msg.TouchEvent}
   */
  public enum TouchEvent
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>DOWN = 0;</code>
     *
     * <pre>
     * 点按下
     * </pre>
     */
    DOWN(0, 0),
    /**
     * <code>MOVE = 1;</code>
     *
     * <pre>
     * 点按下后移动
     * </pre>
     */
    MOVE(1, 1),
    /**
     * <code>UP = 2;</code>
     *
     * <pre>
     * 点抬起
     * </pre>
     */
    UP(2, 2),
    ;

    /**
     * <code>DOWN = 0;</code>
     *
     * <pre>
     * 点按下
     * </pre>
     */
    public static final int DOWN_VALUE = 0;
    /**
     * <code>MOVE = 1;</code>
     *
     * <pre>
     * 点按下后移动
     * </pre>
     */
    public static final int MOVE_VALUE = 1;
    /**
     * <code>UP = 2;</code>
     *
     * <pre>
     * 点抬起
     * </pre>
     */
    public static final int UP_VALUE = 2;


    public final int getNumber() { return value; }

    public static TouchEvent valueOf(int value) {
      switch (value) {
        case 0: return DOWN;
        case 1: return MOVE;
        case 2: return UP;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<TouchEvent>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<TouchEvent>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<TouchEvent>() {
            public TouchEvent findValueByNumber(int number) {
              return TouchEvent.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.hengqian.whiteboard.msg.Whiteboardmsg.getDescriptor().getEnumTypes().get(1);
    }

    private static final TouchEvent[] VALUES = values();

    public static TouchEvent valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private TouchEvent(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:com.hengqian.whiteboard.msg.TouchEvent)
  }

  public interface WhiteBoardMsgOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required .com.hengqian.whiteboard.msg.TypeCommand type = 1;
    /**
     * <code>required .com.hengqian.whiteboard.msg.TypeCommand type = 1;</code>
     */
    boolean hasType();
    /**
     * <code>required .com.hengqian.whiteboard.msg.TypeCommand type = 1;</code>
     */
    com.hengqian.whiteboard.msg.Whiteboardmsg.TypeCommand getType();

    // required string uid = 2;
    /**
     * <code>required string uid = 2;</code>
     */
    boolean hasUid();
    /**
     * <code>required string uid = 2;</code>
     */
    java.lang.String getUid();
    /**
     * <code>required string uid = 2;</code>
     */
    com.google.protobuf.ByteString
        getUidBytes();

    // optional .com.hengqian.whiteboard.msg.TouchEvent touchEvent = 3;
    /**
     * <code>optional .com.hengqian.whiteboard.msg.TouchEvent touchEvent = 3;</code>
     */
    boolean hasTouchEvent();
    /**
     * <code>optional .com.hengqian.whiteboard.msg.TouchEvent touchEvent = 3;</code>
     */
    com.hengqian.whiteboard.msg.Whiteboardmsg.TouchEvent getTouchEvent();

    // optional int32 paintColor = 4;
    /**
     * <code>optional int32 paintColor = 4;</code>
     */
    boolean hasPaintColor();
    /**
     * <code>optional int32 paintColor = 4;</code>
     */
    int getPaintColor();

    // optional int32 paintAlpha = 5;
    /**
     * <code>optional int32 paintAlpha = 5;</code>
     */
    boolean hasPaintAlpha();
    /**
     * <code>optional int32 paintAlpha = 5;</code>
     */
    int getPaintAlpha();

    // optional int32 paintWidth = 6;
    /**
     * <code>optional int32 paintWidth = 6;</code>
     */
    boolean hasPaintWidth();
    /**
     * <code>optional int32 paintWidth = 6;</code>
     */
    int getPaintWidth();

    // repeated .com.hengqian.whiteboard.msg.WhiteBoardMsg.Point point = 7;
    /**
     * <code>repeated .com.hengqian.whiteboard.msg.WhiteBoardMsg.Point point = 7;</code>
     */
    java.util.List<com.hengqian.whiteboard.msg.Whiteboardmsg.WhiteBoardMsg.Point> 
        getPointList();
    /**
     * <code>repeated .com.hengqian.whiteboard.msg.WhiteBoardMsg.Point point = 7;</code>
     */
    com.hengqian.whiteboard.msg.Whiteboardmsg.WhiteBoardMsg.Point getPoint(int index);
    /**
     * <code>repeated .com.hengqian.whiteboard.msg.WhiteBoardMsg.Point point = 7;</code>
     */
    int getPointCount();
    /**
     * <code>repeated .com.hengqian.whiteboard.msg.WhiteBoardMsg.Point point = 7;</code>
     */
    java.util.List<? extends com.hengqian.whiteboard.msg.Whiteboardmsg.WhiteBoardMsg.PointOrBuilder> 
        getPointOrBuilderList();
    /**
     * <code>repeated .com.hengqian.whiteboard.msg.WhiteBoardMsg.Point point = 7;</code>
     */
    com.hengqian.whiteboard.msg.Whiteboardmsg.WhiteBoardMsg.PointOrBuilder getPointOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code com.hengqian.whiteboard.msg.WhiteBoardMsg}
   */
  public static final class WhiteBoardMsg extends
      com.google.protobuf.GeneratedMessage
      implements WhiteBoardMsgOrBuilder {
    // Use WhiteBoardMsg.newBuilder() to construct.
    private WhiteBoardMsg(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private WhiteBoardMsg(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final WhiteBoardMsg defaultInstance;
    public static WhiteBoardMsg getDefaultInstance() {
      return defaultInstance;
    }

    public WhiteBoardMsg getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private WhiteBoardMsg(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              com.hengqian.whiteboard.msg.Whiteboardmsg.TypeCommand value = com.hengqian.whiteboard.msg.Whiteboardmsg.TypeCommand.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                type_ = value;
              }
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              uid_ = input.readBytes();
              break;
            }
            case 24: {
              int rawValue = input.readEnum();
              com.hengqian.whiteboard.msg.Whiteboardmsg.TouchEvent value = com.hengqian.whiteboard.msg.Whiteboardmsg.TouchEvent.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(3, rawValue);
              } else {
                bitField0_ |= 0x00000004;
                touchEvent_ = value;
              }
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              paintColor_ = input.readInt32();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              paintAlpha_ = input.readInt32();
              break;
            }
            case 48: {
              bitField0_ |= 0x00000020;
              paintWidth_ = input.readInt32();
              break;
            }
            case 58: {
              if (!((mutable_bitField0_ & 0x00000040) == 0x00000040)) {
                point_ = new java.util.ArrayList<com.hengqian.whiteboard.msg.Whiteboardmsg.WhiteBoardMsg.Point>();
                mutable_bitField0_ |= 0x00000040;
              }
              point_.add(input.readMessage(com.hengqian.whiteboard.msg.Whiteboardmsg.WhiteBoardMsg.Point.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000040) == 0x00000040)) {
          point_ = java.util.Collections.unmodifiableList(point_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.hengqian.whiteboard.msg.Whiteboardmsg.internal_static_com_hengqian_whiteboard_msg_WhiteBoardMsg_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.hengqian.whiteboard.msg.Whiteboardmsg.internal_static_com_hengqian_whiteboard_msg_WhiteBoardMsg_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.hengqian.whiteboard.msg.Whiteboardmsg.WhiteBoardMsg.class, com.hengqian.whiteboard.msg.Whiteboardmsg.WhiteBoardMsg.Builder.class);
    }

    public static com.google.protobuf.Parser<WhiteBoardMsg> PARSER =
        new com.google.protobuf.AbstractParser<WhiteBoardMsg>() {
      public WhiteBoardMsg parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new WhiteBoardMsg(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<WhiteBoardMsg> getParserForType() {
      return PARSER;
    }

    public interface PointOrBuilder
        extends com.google.protobuf.MessageOrBuilder {

      // required int32 x = 1;
      /**
       * <code>required int32 x = 1;</code>
       */
      boolean hasX();
      /**
       * <code>required int32 x = 1;</code>
       */
      int getX();

      // required int32 y = 2;
      /**
       * <code>required int32 y = 2;</code>
       */
      boolean hasY();
      /**
       * <code>required int32 y = 2;</code>
       */
      int getY();
    }
    /**
     * Protobuf type {@code com.hengqian.whiteboard.msg.WhiteBoardMsg.Point}
     */
    public static final class Point extends
        com.google.protobuf.GeneratedMessage
        implements PointOrBuilder {
      // Use Point.newBuilder() to construct.
      private Point(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
        super(builder);
        this.unknownFields = builder.getUnknownFields();
      }
      private Point(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

      private static final Point defaultInstance;
      public static Point getDefaultInstance() {
        return defaultInstance;
      }

      public Point getDefaultInstanceForType() {
        return defaultInstance;
      }

      private final com.google.protobuf.UnknownFieldSet unknownFields;
      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
          getUnknownFields() {
        return this.unknownFields;
      }
      private Point(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        initFields();
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
              case 8: {
                bitField0_ |= 0x00000001;
                x_ = input.readInt32();
                break;
              }
              case 16: {
                bitField0_ |= 0x00000002;
                y_ = input.readInt32();
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e.getMessage()).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.hengqian.whiteboard.msg.Whiteboardmsg.internal_static_com_hengqian_whiteboard_msg_WhiteBoardMsg_Point_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.hengqian.whiteboard.msg.Whiteboardmsg.internal_static_com_hengqian_whiteboard_msg_WhiteBoardMsg_Point_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.hengqian.whiteboard.msg.Whiteboardmsg.WhiteBoardMsg.Point.class, com.hengqian.whiteboard.msg.Whiteboardmsg.WhiteBoardMsg.Point.Builder.class);
      }

      public static com.google.protobuf.Parser<Point> PARSER =
          new com.google.protobuf.AbstractParser<Point>() {
        public Point parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new Point(input, extensionRegistry);
        }
      };

      @java.lang.Override
      public com.google.protobuf.Parser<Point> getParserForType() {
        return PARSER;
      }

      private int bitField0_;
      // required int32 x = 1;
      public static final int X_FIELD_NUMBER = 1;
      private int x_;
      /**
       * <code>required int32 x = 1;</code>
       */
      public boolean hasX() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 x = 1;</code>
       */
      public int getX() {
        return x_;
      }

      // required int32 y = 2;
      public static final int Y_FIELD_NUMBER = 2;
      private int y_;
      /**
       * <code>required int32 y = 2;</code>
       */
      public boolean hasY() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 y = 2;</code>
       */
      public int getY() {
        return y_;
      }

      private void initFields() {
        x_ = 0;
        y_ = 0;
      }
      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized != -1) return isInitialized == 1;

        if (!hasX()) {
          memoizedIsInitialized = 0;
          return false;
        }
        if (!hasY()) {
          memoizedIsInitialized = 0;
          return false;
        }
        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        getSerializedSize();
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          output.writeInt32(1, x_);
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          output.writeInt32(2, y_);
        }
        getUnknownFields().writeTo(output);
      }

      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;

        size = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(1, x_);
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(2, y_);
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }

      private static final long serialVersionUID = 0L;
      @java.lang.Override
      protected java.lang.Object writeReplace()
          throws java.io.ObjectStreamException {
        return super.writeReplace();
      }

      public static com.hengqian.whiteboard.msg.Whiteboardmsg.WhiteBoardMsg.Point parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.hengqian.whiteboard.msg.Whiteboardmsg.WhiteBoardMsg.Point parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.hengqian.whiteboard.msg.Whiteboardmsg.WhiteBoardMsg.Point parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.hengqian.whiteboard.msg.Whiteboardmsg.WhiteBoardMsg.Point parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.hengqian.whiteboard.msg.Whiteboardmsg.WhiteBoardMsg.Point parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static com.hengqian.whiteboard.msg.Whiteboardmsg.WhiteBoardMsg.Point parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }
      public static com.hengqian.whiteboard.msg.Whiteboardmsg.WhiteBoardMsg.Point parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input);
      }
      public static com.hengqian.whiteboard.msg.Whiteboardmsg.WhiteBoardMsg.Point parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input, extensionRegistry);
      }
      public static com.hengqian.whiteboard.msg.Whiteboardmsg.WhiteBoardMsg.Point parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static com.hengqian.whiteboard.msg.Whiteboardmsg.WhiteBoardMsg.Point parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }

      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(com.hengqian.whiteboard.msg.Whiteboardmsg.WhiteBoardMsg.Point prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code com.hengqian.whiteboard.msg.WhiteBoardMsg.Point}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder>
         implements com.hengqian.whiteboard.msg.Whiteboardmsg.WhiteBoardMsg.PointOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return com.hengqian.whiteboard.msg.Whiteboardmsg.internal_static_com_hengqian_whiteboard_msg_WhiteBoardMsg_Point_descriptor;
        }

        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return com.hengqian.whiteboard.msg.Whiteboardmsg.internal_static_com_hengqian_whiteboard_msg_WhiteBoardMsg_Point_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  com.hengqian.whiteboard.msg.Whiteboardmsg.WhiteBoardMsg.Point.class, com.hengqian.whiteboard.msg.Whiteboardmsg.WhiteBoardMsg.Point.Builder.class);
        }

        // Construct using com.hengqian.whiteboard.msg.Whiteboardmsg.WhiteBoardMsg.Point.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessage.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          }
        }
        private static Builder create() {
          return new Builder();
        }

        public Builder clear() {
          super.clear();
          x_ = 0;
          bitField0_ = (bitField0_ & ~0x00000001);
          y_ = 0;
          bitField0_ = (bitField0_ & ~0x00000002);
          return this;
        }

        public Builder clone() {
          return create().mergeFrom(buildPartial());
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return com.hengqian.whiteboard.msg.Whiteboardmsg.internal_static_com_hengqian_whiteboard_msg_WhiteBoardMsg_Point_descriptor;
        }

        public com.hengqian.whiteboard.msg.Whiteboardmsg.WhiteBoardMsg.Point getDefaultInstanceForType() {
          return com.hengqian.whiteboard.msg.Whiteboardmsg.WhiteBoardMsg.Point.getDefaultInstance();
        }

        public com.hengqian.whiteboard.msg.Whiteboardmsg.WhiteBoardMsg.Point build() {
          com.hengqian.whiteboard.msg.Whiteboardmsg.WhiteBoardMsg.Point result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public com.hengqian.whiteboard.msg.Whiteboardmsg.WhiteBoardMsg.Point buildPartial() {
          com.hengqian.whiteboard.msg.Whiteboardmsg.WhiteBoardMsg.Point result = new com.hengqian.whiteboard.msg.Whiteboardmsg.WhiteBoardMsg.Point(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
            to_bitField0_ |= 0x00000001;
          }
          result.x_ = x_;
          if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
            to_bitField0_ |= 0x00000002;
          }
          result.y_ = y_;
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }

        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof com.hengqian.whiteboard.msg.Whiteboardmsg.WhiteBoardMsg.Point) {
            return mergeFrom((com.hengqian.whiteboard.msg.Whiteboardmsg.WhiteBoardMsg.Point)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(com.hengqian.whiteboard.msg.Whiteboardmsg.WhiteBoardMsg.Point other) {
          if (other == com.hengqian.whiteboard.msg.Whiteboardmsg.WhiteBoardMsg.Point.getDefaultInstance()) return this;
          if (other.hasX()) {
            setX(other.getX());
          }
          if (other.hasY()) {
            setY(other.getY());
          }
          this.mergeUnknownFields(other.getUnknownFields());
          return this;
        }

        public final boolean isInitialized() {
          if (!hasX()) {
            
            return false;
          }
          if (!hasY()) {
            
            return false;
          }
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          com.hengqian.whiteboard.msg.Whiteboardmsg.WhiteBoardMsg.Point parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (com.hengqian.whiteboard.msg.Whiteboardmsg.WhiteBoardMsg.Point) e.getUnfinishedMessage();
            throw e;
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        private int bitField0_;

        // required int32 x = 1;
        private int x_ ;
        /**
         * <code>required int32 x = 1;</code>
         */
        public boolean hasX() {
          return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        /**
         * <code>required int32 x = 1;</code>
         */
        public int getX() {
          return x_;
        }
        /**
         * <code>required int32 x = 1;</code>
         */
        public Builder setX(int value) {
          bitField0_ |= 0x00000001;
          x_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required int32 x = 1;</code>
         */
        public Builder clearX() {
          bitField0_ = (bitField0_ & ~0x00000001);
          x_ = 0;
          onChanged();
          return this;
        }

        // required int32 y = 2;
        private int y_ ;
        /**
         * <code>required int32 y = 2;</code>
         */
        public boolean hasY() {
          return ((bitField0_ & 0x00000002) == 0x00000002);
        }
        /**
         * <code>required int32 y = 2;</code>
         */
        public int getY() {
          return y_;
        }
        /**
         * <code>required int32 y = 2;</code>
         */
        public Builder setY(int value) {
          bitField0_ |= 0x00000002;
          y_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required int32 y = 2;</code>
         */
        public Builder clearY() {
          bitField0_ = (bitField0_ & ~0x00000002);
          y_ = 0;
          onChanged();
          return this;
        }

        // @@protoc_insertion_point(builder_scope:com.hengqian.whiteboard.msg.WhiteBoardMsg.Point)
      }

      static {
        defaultInstance = new Point(true);
        defaultInstance.initFields();
      }

      // @@protoc_insertion_point(class_scope:com.hengqian.whiteboard.msg.WhiteBoardMsg.Point)
    }

    private int bitField0_;
    // required .com.hengqian.whiteboard.msg.TypeCommand type = 1;
    public static final int TYPE_FIELD_NUMBER = 1;
    private com.hengqian.whiteboard.msg.Whiteboardmsg.TypeCommand type_;
    /**
     * <code>required .com.hengqian.whiteboard.msg.TypeCommand type = 1;</code>
     */
    public boolean hasType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .com.hengqian.whiteboard.msg.TypeCommand type = 1;</code>
     */
    public com.hengqian.whiteboard.msg.Whiteboardmsg.TypeCommand getType() {
      return type_;
    }

    // required string uid = 2;
    public static final int UID_FIELD_NUMBER = 2;
    private java.lang.Object uid_;
    /**
     * <code>required string uid = 2;</code>
     */
    public boolean hasUid() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string uid = 2;</code>
     */
    public java.lang.String getUid() {
      java.lang.Object ref = uid_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          uid_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string uid = 2;</code>
     */
    public com.google.protobuf.ByteString
        getUidBytes() {
      java.lang.Object ref = uid_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        uid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional .com.hengqian.whiteboard.msg.TouchEvent touchEvent = 3;
    public static final int TOUCHEVENT_FIELD_NUMBER = 3;
    private com.hengqian.whiteboard.msg.Whiteboardmsg.TouchEvent touchEvent_;
    /**
     * <code>optional .com.hengqian.whiteboard.msg.TouchEvent touchEvent = 3;</code>
     */
    public boolean hasTouchEvent() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional .com.hengqian.whiteboard.msg.TouchEvent touchEvent = 3;</code>
     */
    public com.hengqian.whiteboard.msg.Whiteboardmsg.TouchEvent getTouchEvent() {
      return touchEvent_;
    }

    // optional int32 paintColor = 4;
    public static final int PAINTCOLOR_FIELD_NUMBER = 4;
    private int paintColor_;
    /**
     * <code>optional int32 paintColor = 4;</code>
     */
    public boolean hasPaintColor() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional int32 paintColor = 4;</code>
     */
    public int getPaintColor() {
      return paintColor_;
    }

    // optional int32 paintAlpha = 5;
    public static final int PAINTALPHA_FIELD_NUMBER = 5;
    private int paintAlpha_;
    /**
     * <code>optional int32 paintAlpha = 5;</code>
     */
    public boolean hasPaintAlpha() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional int32 paintAlpha = 5;</code>
     */
    public int getPaintAlpha() {
      return paintAlpha_;
    }

    // optional int32 paintWidth = 6;
    public static final int PAINTWIDTH_FIELD_NUMBER = 6;
    private int paintWidth_;
    /**
     * <code>optional int32 paintWidth = 6;</code>
     */
    public boolean hasPaintWidth() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional int32 paintWidth = 6;</code>
     */
    public int getPaintWidth() {
      return paintWidth_;
    }

    // repeated .com.hengqian.whiteboard.msg.WhiteBoardMsg.Point point = 7;
    public static final int POINT_FIELD_NUMBER = 7;
    private java.util.List<com.hengqian.whiteboard.msg.Whiteboardmsg.WhiteBoardMsg.Point> point_;
    /**
     * <code>repeated .com.hengqian.whiteboard.msg.WhiteBoardMsg.Point point = 7;</code>
     */
    public java.util.List<com.hengqian.whiteboard.msg.Whiteboardmsg.WhiteBoardMsg.Point> getPointList() {
      return point_;
    }
    /**
     * <code>repeated .com.hengqian.whiteboard.msg.WhiteBoardMsg.Point point = 7;</code>
     */
    public java.util.List<? extends com.hengqian.whiteboard.msg.Whiteboardmsg.WhiteBoardMsg.PointOrBuilder> 
        getPointOrBuilderList() {
      return point_;
    }
    /**
     * <code>repeated .com.hengqian.whiteboard.msg.WhiteBoardMsg.Point point = 7;</code>
     */
    public int getPointCount() {
      return point_.size();
    }
    /**
     * <code>repeated .com.hengqian.whiteboard.msg.WhiteBoardMsg.Point point = 7;</code>
     */
    public com.hengqian.whiteboard.msg.Whiteboardmsg.WhiteBoardMsg.Point getPoint(int index) {
      return point_.get(index);
    }
    /**
     * <code>repeated .com.hengqian.whiteboard.msg.WhiteBoardMsg.Point point = 7;</code>
     */
    public com.hengqian.whiteboard.msg.Whiteboardmsg.WhiteBoardMsg.PointOrBuilder getPointOrBuilder(
        int index) {
      return point_.get(index);
    }

    private void initFields() {
      type_ = com.hengqian.whiteboard.msg.Whiteboardmsg.TypeCommand.DrawPoint;
      uid_ = "";
      touchEvent_ = com.hengqian.whiteboard.msg.Whiteboardmsg.TouchEvent.DOWN;
      paintColor_ = 0;
      paintAlpha_ = 0;
      paintWidth_ = 0;
      point_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasUid()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getPointCount(); i++) {
        if (!getPoint(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, type_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getUidBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeEnum(3, touchEvent_.getNumber());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt32(4, paintColor_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeInt32(5, paintAlpha_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeInt32(6, paintWidth_);
      }
      for (int i = 0; i < point_.size(); i++) {
        output.writeMessage(7, point_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, type_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getUidBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(3, touchEvent_.getNumber());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, paintColor_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, paintAlpha_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(6, paintWidth_);
      }
      for (int i = 0; i < point_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(7, point_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.hengqian.whiteboard.msg.Whiteboardmsg.WhiteBoardMsg parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.hengqian.whiteboard.msg.Whiteboardmsg.WhiteBoardMsg parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.hengqian.whiteboard.msg.Whiteboardmsg.WhiteBoardMsg parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.hengqian.whiteboard.msg.Whiteboardmsg.WhiteBoardMsg parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.hengqian.whiteboard.msg.Whiteboardmsg.WhiteBoardMsg parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.hengqian.whiteboard.msg.Whiteboardmsg.WhiteBoardMsg parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.hengqian.whiteboard.msg.Whiteboardmsg.WhiteBoardMsg parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.hengqian.whiteboard.msg.Whiteboardmsg.WhiteBoardMsg parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.hengqian.whiteboard.msg.Whiteboardmsg.WhiteBoardMsg parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.hengqian.whiteboard.msg.Whiteboardmsg.WhiteBoardMsg parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.hengqian.whiteboard.msg.Whiteboardmsg.WhiteBoardMsg prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.hengqian.whiteboard.msg.WhiteBoardMsg}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.hengqian.whiteboard.msg.Whiteboardmsg.WhiteBoardMsgOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.hengqian.whiteboard.msg.Whiteboardmsg.internal_static_com_hengqian_whiteboard_msg_WhiteBoardMsg_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.hengqian.whiteboard.msg.Whiteboardmsg.internal_static_com_hengqian_whiteboard_msg_WhiteBoardMsg_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.hengqian.whiteboard.msg.Whiteboardmsg.WhiteBoardMsg.class, com.hengqian.whiteboard.msg.Whiteboardmsg.WhiteBoardMsg.Builder.class);
      }

      // Construct using com.hengqian.whiteboard.msg.Whiteboardmsg.WhiteBoardMsg.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getPointFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        type_ = com.hengqian.whiteboard.msg.Whiteboardmsg.TypeCommand.DrawPoint;
        bitField0_ = (bitField0_ & ~0x00000001);
        uid_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        touchEvent_ = com.hengqian.whiteboard.msg.Whiteboardmsg.TouchEvent.DOWN;
        bitField0_ = (bitField0_ & ~0x00000004);
        paintColor_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        paintAlpha_ = 0;
        bitField0_ = (bitField0_ & ~0x00000010);
        paintWidth_ = 0;
        bitField0_ = (bitField0_ & ~0x00000020);
        if (pointBuilder_ == null) {
          point_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000040);
        } else {
          pointBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.hengqian.whiteboard.msg.Whiteboardmsg.internal_static_com_hengqian_whiteboard_msg_WhiteBoardMsg_descriptor;
      }

      public com.hengqian.whiteboard.msg.Whiteboardmsg.WhiteBoardMsg getDefaultInstanceForType() {
        return com.hengqian.whiteboard.msg.Whiteboardmsg.WhiteBoardMsg.getDefaultInstance();
      }

      public com.hengqian.whiteboard.msg.Whiteboardmsg.WhiteBoardMsg build() {
        com.hengqian.whiteboard.msg.Whiteboardmsg.WhiteBoardMsg result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.hengqian.whiteboard.msg.Whiteboardmsg.WhiteBoardMsg buildPartial() {
        com.hengqian.whiteboard.msg.Whiteboardmsg.WhiteBoardMsg result = new com.hengqian.whiteboard.msg.Whiteboardmsg.WhiteBoardMsg(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.type_ = type_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.uid_ = uid_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.touchEvent_ = touchEvent_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.paintColor_ = paintColor_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.paintAlpha_ = paintAlpha_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.paintWidth_ = paintWidth_;
        if (pointBuilder_ == null) {
          if (((bitField0_ & 0x00000040) == 0x00000040)) {
            point_ = java.util.Collections.unmodifiableList(point_);
            bitField0_ = (bitField0_ & ~0x00000040);
          }
          result.point_ = point_;
        } else {
          result.point_ = pointBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.hengqian.whiteboard.msg.Whiteboardmsg.WhiteBoardMsg) {
          return mergeFrom((com.hengqian.whiteboard.msg.Whiteboardmsg.WhiteBoardMsg)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.hengqian.whiteboard.msg.Whiteboardmsg.WhiteBoardMsg other) {
        if (other == com.hengqian.whiteboard.msg.Whiteboardmsg.WhiteBoardMsg.getDefaultInstance()) return this;
        if (other.hasType()) {
          setType(other.getType());
        }
        if (other.hasUid()) {
          bitField0_ |= 0x00000002;
          uid_ = other.uid_;
          onChanged();
        }
        if (other.hasTouchEvent()) {
          setTouchEvent(other.getTouchEvent());
        }
        if (other.hasPaintColor()) {
          setPaintColor(other.getPaintColor());
        }
        if (other.hasPaintAlpha()) {
          setPaintAlpha(other.getPaintAlpha());
        }
        if (other.hasPaintWidth()) {
          setPaintWidth(other.getPaintWidth());
        }
        if (pointBuilder_ == null) {
          if (!other.point_.isEmpty()) {
            if (point_.isEmpty()) {
              point_ = other.point_;
              bitField0_ = (bitField0_ & ~0x00000040);
            } else {
              ensurePointIsMutable();
              point_.addAll(other.point_);
            }
            onChanged();
          }
        } else {
          if (!other.point_.isEmpty()) {
            if (pointBuilder_.isEmpty()) {
              pointBuilder_.dispose();
              pointBuilder_ = null;
              point_ = other.point_;
              bitField0_ = (bitField0_ & ~0x00000040);
              pointBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getPointFieldBuilder() : null;
            } else {
              pointBuilder_.addAllMessages(other.point_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasType()) {
          
          return false;
        }
        if (!hasUid()) {
          
          return false;
        }
        for (int i = 0; i < getPointCount(); i++) {
          if (!getPoint(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.hengqian.whiteboard.msg.Whiteboardmsg.WhiteBoardMsg parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.hengqian.whiteboard.msg.Whiteboardmsg.WhiteBoardMsg) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required .com.hengqian.whiteboard.msg.TypeCommand type = 1;
      private com.hengqian.whiteboard.msg.Whiteboardmsg.TypeCommand type_ = com.hengqian.whiteboard.msg.Whiteboardmsg.TypeCommand.DrawPoint;
      /**
       * <code>required .com.hengqian.whiteboard.msg.TypeCommand type = 1;</code>
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .com.hengqian.whiteboard.msg.TypeCommand type = 1;</code>
       */
      public com.hengqian.whiteboard.msg.Whiteboardmsg.TypeCommand getType() {
        return type_;
      }
      /**
       * <code>required .com.hengqian.whiteboard.msg.TypeCommand type = 1;</code>
       */
      public Builder setType(com.hengqian.whiteboard.msg.Whiteboardmsg.TypeCommand value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required .com.hengqian.whiteboard.msg.TypeCommand type = 1;</code>
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        type_ = com.hengqian.whiteboard.msg.Whiteboardmsg.TypeCommand.DrawPoint;
        onChanged();
        return this;
      }

      // required string uid = 2;
      private java.lang.Object uid_ = "";
      /**
       * <code>required string uid = 2;</code>
       */
      public boolean hasUid() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string uid = 2;</code>
       */
      public java.lang.String getUid() {
        java.lang.Object ref = uid_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          uid_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string uid = 2;</code>
       */
      public com.google.protobuf.ByteString
          getUidBytes() {
        java.lang.Object ref = uid_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          uid_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string uid = 2;</code>
       */
      public Builder setUid(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        uid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string uid = 2;</code>
       */
      public Builder clearUid() {
        bitField0_ = (bitField0_ & ~0x00000002);
        uid_ = getDefaultInstance().getUid();
        onChanged();
        return this;
      }
      /**
       * <code>required string uid = 2;</code>
       */
      public Builder setUidBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        uid_ = value;
        onChanged();
        return this;
      }

      // optional .com.hengqian.whiteboard.msg.TouchEvent touchEvent = 3;
      private com.hengqian.whiteboard.msg.Whiteboardmsg.TouchEvent touchEvent_ = com.hengqian.whiteboard.msg.Whiteboardmsg.TouchEvent.DOWN;
      /**
       * <code>optional .com.hengqian.whiteboard.msg.TouchEvent touchEvent = 3;</code>
       */
      public boolean hasTouchEvent() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional .com.hengqian.whiteboard.msg.TouchEvent touchEvent = 3;</code>
       */
      public com.hengqian.whiteboard.msg.Whiteboardmsg.TouchEvent getTouchEvent() {
        return touchEvent_;
      }
      /**
       * <code>optional .com.hengqian.whiteboard.msg.TouchEvent touchEvent = 3;</code>
       */
      public Builder setTouchEvent(com.hengqian.whiteboard.msg.Whiteboardmsg.TouchEvent value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000004;
        touchEvent_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional .com.hengqian.whiteboard.msg.TouchEvent touchEvent = 3;</code>
       */
      public Builder clearTouchEvent() {
        bitField0_ = (bitField0_ & ~0x00000004);
        touchEvent_ = com.hengqian.whiteboard.msg.Whiteboardmsg.TouchEvent.DOWN;
        onChanged();
        return this;
      }

      // optional int32 paintColor = 4;
      private int paintColor_ ;
      /**
       * <code>optional int32 paintColor = 4;</code>
       */
      public boolean hasPaintColor() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional int32 paintColor = 4;</code>
       */
      public int getPaintColor() {
        return paintColor_;
      }
      /**
       * <code>optional int32 paintColor = 4;</code>
       */
      public Builder setPaintColor(int value) {
        bitField0_ |= 0x00000008;
        paintColor_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 paintColor = 4;</code>
       */
      public Builder clearPaintColor() {
        bitField0_ = (bitField0_ & ~0x00000008);
        paintColor_ = 0;
        onChanged();
        return this;
      }

      // optional int32 paintAlpha = 5;
      private int paintAlpha_ ;
      /**
       * <code>optional int32 paintAlpha = 5;</code>
       */
      public boolean hasPaintAlpha() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional int32 paintAlpha = 5;</code>
       */
      public int getPaintAlpha() {
        return paintAlpha_;
      }
      /**
       * <code>optional int32 paintAlpha = 5;</code>
       */
      public Builder setPaintAlpha(int value) {
        bitField0_ |= 0x00000010;
        paintAlpha_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 paintAlpha = 5;</code>
       */
      public Builder clearPaintAlpha() {
        bitField0_ = (bitField0_ & ~0x00000010);
        paintAlpha_ = 0;
        onChanged();
        return this;
      }

      // optional int32 paintWidth = 6;
      private int paintWidth_ ;
      /**
       * <code>optional int32 paintWidth = 6;</code>
       */
      public boolean hasPaintWidth() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional int32 paintWidth = 6;</code>
       */
      public int getPaintWidth() {
        return paintWidth_;
      }
      /**
       * <code>optional int32 paintWidth = 6;</code>
       */
      public Builder setPaintWidth(int value) {
        bitField0_ |= 0x00000020;
        paintWidth_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 paintWidth = 6;</code>
       */
      public Builder clearPaintWidth() {
        bitField0_ = (bitField0_ & ~0x00000020);
        paintWidth_ = 0;
        onChanged();
        return this;
      }

      // repeated .com.hengqian.whiteboard.msg.WhiteBoardMsg.Point point = 7;
      private java.util.List<com.hengqian.whiteboard.msg.Whiteboardmsg.WhiteBoardMsg.Point> point_ =
        java.util.Collections.emptyList();
      private void ensurePointIsMutable() {
        if (!((bitField0_ & 0x00000040) == 0x00000040)) {
          point_ = new java.util.ArrayList<com.hengqian.whiteboard.msg.Whiteboardmsg.WhiteBoardMsg.Point>(point_);
          bitField0_ |= 0x00000040;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          com.hengqian.whiteboard.msg.Whiteboardmsg.WhiteBoardMsg.Point, com.hengqian.whiteboard.msg.Whiteboardmsg.WhiteBoardMsg.Point.Builder, com.hengqian.whiteboard.msg.Whiteboardmsg.WhiteBoardMsg.PointOrBuilder> pointBuilder_;

      /**
       * <code>repeated .com.hengqian.whiteboard.msg.WhiteBoardMsg.Point point = 7;</code>
       */
      public java.util.List<com.hengqian.whiteboard.msg.Whiteboardmsg.WhiteBoardMsg.Point> getPointList() {
        if (pointBuilder_ == null) {
          return java.util.Collections.unmodifiableList(point_);
        } else {
          return pointBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .com.hengqian.whiteboard.msg.WhiteBoardMsg.Point point = 7;</code>
       */
      public int getPointCount() {
        if (pointBuilder_ == null) {
          return point_.size();
        } else {
          return pointBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .com.hengqian.whiteboard.msg.WhiteBoardMsg.Point point = 7;</code>
       */
      public com.hengqian.whiteboard.msg.Whiteboardmsg.WhiteBoardMsg.Point getPoint(int index) {
        if (pointBuilder_ == null) {
          return point_.get(index);
        } else {
          return pointBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .com.hengqian.whiteboard.msg.WhiteBoardMsg.Point point = 7;</code>
       */
      public Builder setPoint(
          int index, com.hengqian.whiteboard.msg.Whiteboardmsg.WhiteBoardMsg.Point value) {
        if (pointBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePointIsMutable();
          point_.set(index, value);
          onChanged();
        } else {
          pointBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.hengqian.whiteboard.msg.WhiteBoardMsg.Point point = 7;</code>
       */
      public Builder setPoint(
          int index, com.hengqian.whiteboard.msg.Whiteboardmsg.WhiteBoardMsg.Point.Builder builderForValue) {
        if (pointBuilder_ == null) {
          ensurePointIsMutable();
          point_.set(index, builderForValue.build());
          onChanged();
        } else {
          pointBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.hengqian.whiteboard.msg.WhiteBoardMsg.Point point = 7;</code>
       */
      public Builder addPoint(com.hengqian.whiteboard.msg.Whiteboardmsg.WhiteBoardMsg.Point value) {
        if (pointBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePointIsMutable();
          point_.add(value);
          onChanged();
        } else {
          pointBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .com.hengqian.whiteboard.msg.WhiteBoardMsg.Point point = 7;</code>
       */
      public Builder addPoint(
          int index, com.hengqian.whiteboard.msg.Whiteboardmsg.WhiteBoardMsg.Point value) {
        if (pointBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePointIsMutable();
          point_.add(index, value);
          onChanged();
        } else {
          pointBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.hengqian.whiteboard.msg.WhiteBoardMsg.Point point = 7;</code>
       */
      public Builder addPoint(
          com.hengqian.whiteboard.msg.Whiteboardmsg.WhiteBoardMsg.Point.Builder builderForValue) {
        if (pointBuilder_ == null) {
          ensurePointIsMutable();
          point_.add(builderForValue.build());
          onChanged();
        } else {
          pointBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.hengqian.whiteboard.msg.WhiteBoardMsg.Point point = 7;</code>
       */
      public Builder addPoint(
          int index, com.hengqian.whiteboard.msg.Whiteboardmsg.WhiteBoardMsg.Point.Builder builderForValue) {
        if (pointBuilder_ == null) {
          ensurePointIsMutable();
          point_.add(index, builderForValue.build());
          onChanged();
        } else {
          pointBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.hengqian.whiteboard.msg.WhiteBoardMsg.Point point = 7;</code>
       */
      public Builder addAllPoint(
          java.lang.Iterable<? extends com.hengqian.whiteboard.msg.Whiteboardmsg.WhiteBoardMsg.Point> values) {
        if (pointBuilder_ == null) {
          ensurePointIsMutable();
          super.addAll(values, point_);
          onChanged();
        } else {
          pointBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .com.hengqian.whiteboard.msg.WhiteBoardMsg.Point point = 7;</code>
       */
      public Builder clearPoint() {
        if (pointBuilder_ == null) {
          point_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000040);
          onChanged();
        } else {
          pointBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .com.hengqian.whiteboard.msg.WhiteBoardMsg.Point point = 7;</code>
       */
      public Builder removePoint(int index) {
        if (pointBuilder_ == null) {
          ensurePointIsMutable();
          point_.remove(index);
          onChanged();
        } else {
          pointBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .com.hengqian.whiteboard.msg.WhiteBoardMsg.Point point = 7;</code>
       */
      public com.hengqian.whiteboard.msg.Whiteboardmsg.WhiteBoardMsg.Point.Builder getPointBuilder(
          int index) {
        return getPointFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .com.hengqian.whiteboard.msg.WhiteBoardMsg.Point point = 7;</code>
       */
      public com.hengqian.whiteboard.msg.Whiteboardmsg.WhiteBoardMsg.PointOrBuilder getPointOrBuilder(
          int index) {
        if (pointBuilder_ == null) {
          return point_.get(index);  } else {
          return pointBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .com.hengqian.whiteboard.msg.WhiteBoardMsg.Point point = 7;</code>
       */
      public java.util.List<? extends com.hengqian.whiteboard.msg.Whiteboardmsg.WhiteBoardMsg.PointOrBuilder> 
           getPointOrBuilderList() {
        if (pointBuilder_ != null) {
          return pointBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(point_);
        }
      }
      /**
       * <code>repeated .com.hengqian.whiteboard.msg.WhiteBoardMsg.Point point = 7;</code>
       */
      public com.hengqian.whiteboard.msg.Whiteboardmsg.WhiteBoardMsg.Point.Builder addPointBuilder() {
        return getPointFieldBuilder().addBuilder(
            com.hengqian.whiteboard.msg.Whiteboardmsg.WhiteBoardMsg.Point.getDefaultInstance());
      }
      /**
       * <code>repeated .com.hengqian.whiteboard.msg.WhiteBoardMsg.Point point = 7;</code>
       */
      public com.hengqian.whiteboard.msg.Whiteboardmsg.WhiteBoardMsg.Point.Builder addPointBuilder(
          int index) {
        return getPointFieldBuilder().addBuilder(
            index, com.hengqian.whiteboard.msg.Whiteboardmsg.WhiteBoardMsg.Point.getDefaultInstance());
      }
      /**
       * <code>repeated .com.hengqian.whiteboard.msg.WhiteBoardMsg.Point point = 7;</code>
       */
      public java.util.List<com.hengqian.whiteboard.msg.Whiteboardmsg.WhiteBoardMsg.Point.Builder> 
           getPointBuilderList() {
        return getPointFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.hengqian.whiteboard.msg.Whiteboardmsg.WhiteBoardMsg.Point, com.hengqian.whiteboard.msg.Whiteboardmsg.WhiteBoardMsg.Point.Builder, com.hengqian.whiteboard.msg.Whiteboardmsg.WhiteBoardMsg.PointOrBuilder> 
          getPointFieldBuilder() {
        if (pointBuilder_ == null) {
          pointBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.hengqian.whiteboard.msg.Whiteboardmsg.WhiteBoardMsg.Point, com.hengqian.whiteboard.msg.Whiteboardmsg.WhiteBoardMsg.Point.Builder, com.hengqian.whiteboard.msg.Whiteboardmsg.WhiteBoardMsg.PointOrBuilder>(
                  point_,
                  ((bitField0_ & 0x00000040) == 0x00000040),
                  getParentForChildren(),
                  isClean());
          point_ = null;
        }
        return pointBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:com.hengqian.whiteboard.msg.WhiteBoardMsg)
    }

    static {
      defaultInstance = new WhiteBoardMsg(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.hengqian.whiteboard.msg.WhiteBoardMsg)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_hengqian_whiteboard_msg_WhiteBoardMsg_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_hengqian_whiteboard_msg_WhiteBoardMsg_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_hengqian_whiteboard_msg_WhiteBoardMsg_Point_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_hengqian_whiteboard_msg_WhiteBoardMsg_Point_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023whiteboardmsg.proto\022\033com.hengqian.whit" +
      "eboard.msg\"\255\002\n\rWhiteBoardMsg\0226\n\004type\030\001 \002" +
      "(\0162(.com.hengqian.whiteboard.msg.TypeCom" +
      "mand\022\013\n\003uid\030\002 \002(\t\022;\n\ntouchEvent\030\003 \001(\0162\'." +
      "com.hengqian.whiteboard.msg.TouchEvent\022\022" +
      "\n\npaintColor\030\004 \001(\005\022\022\n\npaintAlpha\030\005 \001(\005\022\022" +
      "\n\npaintWidth\030\006 \001(\005\022?\n\005point\030\007 \003(\01320.com." +
      "hengqian.whiteboard.msg.WhiteBoardMsg.Po" +
      "int\032\035\n\005Point\022\t\n\001x\030\001 \002(\005\022\t\n\001y\030\002 \002(\005*N\n\013Ty" +
      "peCommand\022\016\n\tDrawPoint\020\221N\022\r\n\010DrawUndo\020\222N",
      "\022\021\n\014DrawClearAll\020\223N\022\r\n\010DrawQuit\020\224N*(\n\nTo" +
      "uchEvent\022\010\n\004DOWN\020\000\022\010\n\004MOVE\020\001\022\006\n\002UP\020\002"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_hengqian_whiteboard_msg_WhiteBoardMsg_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_hengqian_whiteboard_msg_WhiteBoardMsg_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_hengqian_whiteboard_msg_WhiteBoardMsg_descriptor,
              new java.lang.String[] { "Type", "Uid", "TouchEvent", "PaintColor", "PaintAlpha", "PaintWidth", "Point", });
          internal_static_com_hengqian_whiteboard_msg_WhiteBoardMsg_Point_descriptor =
            internal_static_com_hengqian_whiteboard_msg_WhiteBoardMsg_descriptor.getNestedTypes().get(0);
          internal_static_com_hengqian_whiteboard_msg_WhiteBoardMsg_Point_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_hengqian_whiteboard_msg_WhiteBoardMsg_Point_descriptor,
              new java.lang.String[] { "X", "Y", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
